---
# tasks file for web

- name: install apache
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - httpd-tools

- name: copy pache index file
  copy: src=index.html dest=/var/www/html/index.html
  tags: apache
  notify: restart apache service
